-- File: full_adder.vhd
-- Generated by MyHDL 0.9.0
-- Date: Sat Apr 22 14:19:03 2017


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity full_adder is
    port (
        A: in std_logic;
        B: in std_logic;
        C_in: in std_logic;
        KeyOne: in std_logic;
        KeyTwo: in std_logic;
        KeyThree: in std_logic;
        Sum_out: out std_logic;
        C_out: out std_logic
    );
end entity full_adder;
-- full adder circuit
-- {A,B,C} --- inputs
-- {Sum_out,C_out} -- outputs

architecture MyHDL of full_adder is






begin






Sum_out <= (((A xor B) xor KeyOne) xor C_in);
C_out <= (((((A xor B) xor C_in) and C_in) xor KeyTwo) or ((A and B) xor KeyThree));

end architecture MyHDL;
